###

POST http://localhost:8000/api/user
Content-Type: application/json

{
  "email":"ariunaa@gmail.com",
  "password":"Arinaa"
}

###

POST http://localhost:8000/api/user/login
Content-Type: application/json

{
  "email":"ariunaa@gmail.com",
  "password":"Arinaa"
}




###
GET http://localhost:8000/api/user?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MWJiMzA4MWVkMWE0ZGE1YTRjOTgyZiIsInBhc3N3b3JkIjoiJDJiJDEwJDF3Z2dEOFNlSy8xbW5lWlV3d3R2Q09MWHc0V3NYclhXcVVOWXJUWmFNTWs0dVZVandkL3FXIiwiZW1haWwiOiJPeXVrYUBnbWFpbC5jb20iLCJfX3YiOjB9LCJpYXQiOjE2Nzk1MzY5NjksImV4cCI6MTY3OTU0NDE2OX0.6res6CzbNlqFCuErLNnu40OPNXr4E5L1qcbh_Mp-_Qo







