###

POST http://localhost:8000/api/user
Content-Type: application/json


{
  "email":"cfdsvfv@gmail.com",
  "password":"Ariuuunaa",
  "username" : "kfuhdsj"
}

###

POST http://localhost:8000/api/user/login
Content-Type: application/json


{
  "email":"1123@gmail.com",
  "password":"Ariuuunaa"
}




###
GET http://localhost:8000/api/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MWQxMjFjMGUwYWI4YmM5MDA3Yjg1ZiIsInVzZXJuYW1lIjoiaGkiLCJwYXNzd29yZCI6IiQyYiQxMCRpdjhScFRsODBsLk5rY1RHZWRHVHB1aXF4d1hTWDdDWWZVY21VLks5QUoyZVRYSUVDbnEwaSIsImVtYWlsIjoiMTEyM0BnbWFpbC5jb20iLCJfX3YiOjB9LCJpYXQiOjE2Nzk2MjY3OTgsImV4cCI6MTY3OTYzMzk5OH0.gjPkDVGcDOefq_nJBCUI8DsDJhpOPoHvvok6cDZuzM0





